export const CARS_FETCH_REQUEST = '@Car/CARS_FETCH_REQUEST';
export const CARS_FETCH_SUCCESS = '@Car/CARS_FETCH_SUCCESS';
export const CARS_FETCH_FAIL = '@Car/CARS_FETCH_FAIL';

export const CAR_MODELS_FILTER_FETCH_REQUEST = '@Car/CAR_MODELS_FILTER_FETCH_REQUEST';
export const CAR_MODELS_FILTER_FETCH_SUCCESS = '@Car/CAR_MODELS_FILTER_FETCH_SUCCESS';
export const CAR_MODELS_FILTER_FETCH_FAIL = '@Car/CAR_MODELS_FILTER_FETCH_FAIL';

export const CAR_MODELS_CATALOG_FETCH_REQUEST = '@Car/CAR_MODELS_CATALOG_FETCH_REQUEST';
export const CAR_MODELS_CATALOG_FETCH_SUCCESS = '@Car/CAR_MODELS_CATALOG_FETCH_SUCCESS';
export const CAR_MODELS_CATALOG_FETCH_FAIL = '@Car/CAR_MODELS_CATALOG_FETCH_FAIL';

export const CAR_CATEGORIES_FILTER_FETCH_REQUEST = '@Car/CAR_CATEGORIES_FILTER_FETCH_REQUEST';
export const CAR_CATEGORIES_FILTER_FETCH_SUCCESS = '@Car/CAR_CATEGORIES_FILTER_FETCH_SUCCESS';
export const CAR_CATEGORIES_FILTER_FETCH_FAIL = '@Car/CAR_CATEGORIES_FILTER_FETCH_FAIL';

export const CAR_CATEGORIES_CATALOG_FETCH_REQUEST = '@Car/CAR_CATEGORIES_CATALOG_FETCH_REQUEST';
export const CAR_CATEGORIES_CATALOG_FETCH_SUCCESS = '@Car/CAR_CATEGORIES_CATALOG_FETCH_SUCCESS';
export const CAR_CATEGORIES_CATALOG_FETCH_FAIL = '@Car/CAR_CATEGORIES_CATALOG_FETCH_FAIL';

export const CLEAR_FETCH_ERRORS = '@Car/CLEAR_FETCH_ERRORS';