export const CARS_FETCH_REQUEST = '@car/CARS_FETCH_REQUEST';
export const CARS_FETCH_SUCCESS = '@car/CARS_FETCH_SUCCESS';
export const CARS_FETCH_FAIL = '@car/CARS_FETCH_FAIL';

export const CAR_MODELS_FILTER_FETCH_REQUEST = '@car/CAR_MODELS_FILTER_FETCH_REQUEST';
export const CAR_MODELS_FILTER_FETCH_SUCCESS = '@car/CAR_MODELS_FILTER_FETCH_SUCCESS';
export const CAR_MODELS_FILTER_FETCH_FAIL = '@car/CAR_MODELS_FILTER_FETCH_FAIL';

export const CAR_MODELS_CATALOG_FETCH_REQUEST = '@car/CAR_MODELS_CATALOG_FETCH_REQUEST';
export const CAR_MODELS_CATALOG_FETCH_SUCCESS = '@car/CAR_MODELS_CATALOG_FETCH_SUCCESS';
export const CAR_MODELS_CATALOG_FETCH_FAIL = '@car/CAR_MODELS_CATALOG_FETCH_FAIL';

export const CAR_CATEGORIES_FILTER_FETCH_REQUEST = '@car/CAR_CATEGORIES_FILTER_FETCH_REQUEST';
export const CAR_CATEGORIES_FILTER_FETCH_SUCCESS = '@car/CAR_CATEGORIES_FILTER_FETCH_SUCCESS';
export const CAR_CATEGORIES_FILTER_FETCH_FAIL = '@car/CAR_CATEGORIES_FILTER_FETCH_FAIL';

export const CAR_CATEGORIES_CATALOG_FETCH_REQUEST = '@car/CAR_CATEGORIES_CATALOG_FETCH_REQUEST';
export const CAR_CATEGORIES_CATALOG_FETCH_SUCCESS = '@car/CAR_CATEGORIES_CATALOG_FETCH_SUCCESS';
export const CAR_CATEGORIES_CATALOG_FETCH_FAIL = '@car/CAR_CATEGORIES_CATALOG_FETCH_FAIL';

export const CLEAR_FETCH_ERRORS = '@car/CLEAR_FETCH_ERRORS';