export const TRANSPORTER_CITIES_FETCH_REQUEST = '@transporter/TRANSPORTER_CITIES_FETCH_REQUEST';
export const TRANSPORTER_CITIES_FETCH_SUCCESS = '@transporter/TRANSPORTER_CITIES_FETCH_SUCCESS';
export const TRANSPORTER_CITIES_FETCH_FAIL = '@transporter/TRANSPORTER_CITIES_FETCH_FAIL';

export const TRANSPORTER_WAREHOUSES_FETCH_REQUEST = '@transporter/TRANSPORTER_WAREHOUSES_FETCH_REQUEST';
export const TRANSPORTER_WAREHOUSES_FETCH_SUCCESS = '@transporter/TRANSPORTER_WAREHOUSES_FETCH_SUCCESS';
export const TRANSPORTER_WAREHOUSES_FETCH_FAIL = '@transporter/TRANSPORTER_WAREHOUSES_FETCH_FAIL';

export const DELIVERY_METHODS_FETCH_REQUEST = '@transporter/DELIVERY_METHODS_FETCH_REQUEST';
export const DELIVERY_METHODS_FETCH_SUCCESS = '@transporter/DELIVERY_METHODS_FETCH_SUCCESS';
export const DELIVERY_METHODS_FETCH_FAIL = '@transporter/DELIVERY_METHODS_FETCH_FAIL';

export const TRANSPORTERS_FETCH_REQUEST = '@transporter/TRANSPORTERS_FETCH_REQUEST';
export const TRANSPORTERS_FETCH_SUCCESS = '@transporter/TRANSPORTERS_FETCH_SUCCESS';
export const TRANSPORTERS_FETCH_FAIL = '@transporter/TRANSPORTERS_FETCH_FAIL';