export const TRANSPORTER_CITIES_FETCH_REQUEST = '@transporter/TRANSPORTER_CITIES_FETCH_REQUEST';
export const TRANSPORTER_CITIES_FETCH_SUCCESS = '@transporter/TRANSPORTER_CITIES_FETCH_SUCCESS';
export const TRANSPORTER_CITIES_FETCH_FAIL = '@transporter/TRANSPORTER_CITIES_FETCH_FAIL';

export const TRANSPORTER_WAREHOUSES_FETCH_REQUEST = '@transporter/TRANSPORTER_WAREHOUSES_FETCH_REQUEST';
export const TRANSPORTER_WAREHOUSES_FETCH_SUCCESS = '@transporter/TRANSPORTER_WAREHOUSES_FETCH_SUCCESS';
export const TRANSPORTER_WAREHOUSES_FETCH_FAIL = '@transporter/TRANSPORTER_WAREHOUSES_FETCH_FAIL';
