export const TRANSPORTER_CITIES_FETCH_REQUEST = '@Transporter/TRANSPORTER_CITIES_FETCH_REQUEST';
export const TRANSPORTER_CITIES_FETCH_SUCCESS = '@Transporter/TRANSPORTER_CITIES_FETCH_SUCCESS';
export const TRANSPORTER_CITIES_FETCH_FAIL = '@Transporter/TRANSPORTER_CITIES_FETCH_FAIL';

export const TRANSPORTER_WAREHOUSES_FETCH_REQUEST = '@Transporter/TRANSPORTER_WAREHOUSES_FETCH_REQUEST';
export const TRANSPORTER_WAREHOUSES_FETCH_SUCCESS = '@Transporter/TRANSPORTER_WAREHOUSES_FETCH_SUCCESS';
export const TRANSPORTER_WAREHOUSES_FETCH_FAIL = '@Transporter/TRANSPORTER_WAREHOUSES_FETCH_FAIL';

export const DELIVERY_METHODS_FETCH_REQUEST = '@Transporter/DELIVERY_METHODS_FETCH_REQUEST';
export const DELIVERY_METHODS_FETCH_SUCCESS = '@Transporter/DELIVERY_METHODS_FETCH_SUCCESS';
export const DELIVERY_METHODS_FETCH_FAIL = '@Transporter/DELIVERY_METHODS_FETCH_FAIL';

export const TRANSPORTERS_FETCH_REQUEST = '@Transporter/TRANSPORTERS_FETCH_REQUEST';
export const TRANSPORTERS_FETCH_SUCCESS = '@Transporter/TRANSPORTERS_FETCH_SUCCESS';
export const TRANSPORTERS_FETCH_FAIL = '@Transporter/TRANSPORTERS_FETCH_FAIL';