export const CARS_FETCH_REQUEST = '@CarContainer/CARS_FETCH_REQUEST';
export const CARS_FETCH_SUCCESS = '@CarContainer/CARS_FETCH_SUCCESS';
export const CARS_FETCH_FAIL = '@CarContainer/CARS_FETCH_FAIL';

export const CAR_MODELS_FILTER_FETCH_REQUEST = '@CarContainer/CAR_MODELS_FILTER_FETCH_REQUEST';
export const CAR_MODELS_FILTER_FETCH_SUCCESS = '@CarContainer/CAR_MODELS_FILTER_FETCH_SUCCESS';
export const CAR_MODELS_FILTER_FETCH_FAIL = '@CarContainer/CAR_MODELS_FILTER_FETCH_FAIL';

export const CAR_MODELS_CATALOG_FETCH_REQUEST = '@CarContainer/CAR_MODELS_CATALOG_FETCH_REQUEST';
export const CAR_MODELS_CATALOG_FETCH_SUCCESS = '@CarContainer/CAR_MODELS_CATALOG_FETCH_SUCCESS';
export const CAR_MODELS_CATALOG_FETCH_FAIL = '@CarContainer/CAR_MODELS_CATALOG_FETCH_FAIL';

export const CAR_CATEGORIES_FILTER_FETCH_REQUEST = '@CarContainer/CAR_CATEGORIES_FILTER_FETCH_REQUEST';
export const CAR_CATEGORIES_FILTER_FETCH_SUCCESS = '@CarContainer/CAR_CATEGORIES_FILTER_FETCH_SUCCESS';
export const CAR_CATEGORIES_FILTER_FETCH_FAIL = '@CarContainer/CAR_CATEGORIES_FILTER_FETCH_FAIL';

export const CAR_CATEGORIES_CATALOG_FETCH_REQUEST = '@CarContainer/CAR_CATEGORIES_CATALOG_FETCH_REQUEST';
export const CAR_CATEGORIES_CATALOG_FETCH_SUCCESS = '@CarContainer/CAR_CATEGORIES_CATALOG_FETCH_SUCCESS';
export const CAR_CATEGORIES_CATALOG_FETCH_FAIL = '@CarContainer/CAR_CATEGORIES_CATALOG_FETCH_FAIL';

export const CLEAR_FETCH_ERRORS = '@CarContainer/CLEAR_FETCH_ERRORS';