export const COMMENTS_FETCH_REQUEST = '@Comments/COMMENTS_FETCH_REQUEST';
export const COMMENTS_FETCH_SUCCESS = '@Comments/COMMENTS_FETCH_SUCCESS';
export const COMMENTS_FETCH_FAIL = '@Comments/COMMENTS_FETCH_FAIL';

export const DELETE_COMMENT_FETCH_REQUEST = '@Comments/DELETE_COMMENT_FETCH_REQUEST';
export const DELETE_COMMENT_FETCH_SUCCESS = '@Comments/DELETE_COMMENT_FETCH_SUCCESS';
export const DELETE_COMMENT_FETCH_FAIL = '@Comments/DELETE_COMMENT_FETCH_FAIL';

export const SAVE_COMMENT_FETCH_REQUEST = '@Comments/SAVE_COMMENT_FETCH_REQUEST';
export const SAVE_COMMENT_FETCH_SUCCESS = '@Comments/SAVE_COMMENT_FETCH_SUCCESS';
export const SAVE_COMMENT_FETCH_FAIL = '@Comments/SAVE_COMMENT_FETCH_FAIL';