export const PUT_PRODUCT_INTO_CART = '@CartContainer/PUT_PRODUCT_INTO_CART';
export const RESET_POPUP_PRODUCT_TO_CART_ADDED = '@CartContainer/RESET_POPUP_PRODUCT_TO_CART_ADDED';
export const CHANGE_PRODUCT_BUY_QUANTITY = '@CartContainer/CHANGE_PRODUCT_BUY_QUANTITY';
export const DELETE_PRODUCT_ITEM_FROM_CART = '@CartContainer/DELETE_PRODUCT_ITEM_FROM_CART';
export const CLEAR_CART = '@CartContainer/CLEAR_CART';