export const PUT_PRODUCT_INTO_CART = '@cart/PUT_PRODUCT_INTO_CART';
export const RESET_POPUP_PRODUCT_TO_CART_ADDED = '@cart/RESET_POPUP_PRODUCT_TO_CART_ADDED';
export const CHANGE_PRODUCT_BUY_QUANTITY = '@cart/CHANGE_PRODUCT_BUY_QUANTITY';
export const DELETE_PRODUCT_ITEM_FROM_CART = '@cart/DELETE_PRODUCT_ITEM_FROM_CART';
export const CLEAR_CART = '@cart/CLEAR_CART';