export const PUT_PRODUCT_INTO_CART = '@Cart/PUT_PRODUCT_INTO_CART';
export const RESET_POPUP_PRODUCT_TO_CART_ADDED = '@Cart/RESET_POPUP_PRODUCT_TO_CART_ADDED';
export const CHANGE_PRODUCT_BUY_QUANTITY = '@Cart/CHANGE_PRODUCT_BUY_QUANTITY';
export const DELETE_PRODUCT_ITEM_FROM_CART = '@Cart/DELETE_PRODUCT_ITEM_FROM_CART';
export const CLEAR_CART = '@Cart/CLEAR_CART';