export const LOGIN_USER_REQUEST = '@User/LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = '@User/LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = '@User/LOGIN_USER_FAIL';

export const REGISTER_USER_REQUEST = '@User/REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = '@User/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = '@User/REGISTER_USER_FAIL';

export const VALIDATE_NAME_REQUEST = '@User/VALIDATE_NAME_REQUEST';
export const VALIDATE_NAME_SUCCESS = '@User/VALIDATE_NAME_SUCCESS';
export const VALIDATE_NAME_FAIL = '@User/VALIDATE_NAME_FAIL';

export const VALIDATE_EMAIL_REQUEST = '@User/VALIDATE_EMAIL_REQUEST';
export const VALIDATE_EMAIL_SUCCESS = '@User/VALIDATE_EMAIL_SUCCESS';
export const VALIDATE_EMAIL_FAIL = '@User/VALIDATE_EMAIL_FAIL';

export const LOGOUT_USER = '@User/LOGOUT_USER';

export const CLEAR_ERROR_LOGIN = '@User/CLEAR_ERROR_LOGIN';

export const SAVE_ORDER_TAB_DATA = '@User/SAVE_ORDER_TAB_DATA';
export const SAVE_PAYMENT_TAB_DATA = '@User/SAVE_PAYMENT_TAB_DATA';
export const SAVE_DELIVERY_TAB_DATA = '@User/SAVE_DELIVERY_TAB_DATA';

export const SAVE_USER_PHONE = '@User/SAVE_USER_PHONE';

export const SAVE_USER_DATA_REQUEST = '@User/SAVE_USER_DATA_REQUEST';
export const SAVE_USER_DATA_SUCCESS = '@User/SAVE_USER_DATA_SUCCESS';
export const SAVE_USER_DATA_FAIL = '@User/SAVE_USER_DATA_FAIL';

export const REFRESH_USER_DETAIL = '@User/REFRESH_USER_DETAIL';

export const ORDERS_LIST_FETCH_REQUEST = '@User/ORDERS_LIST_FETCH_REQUEST';
export const ORDERS_LIST_FETCH_SUCCESS = '@User/ORDERS_LIST_FETCH_SUCCESS';
export const ORDERS_LIST_FETCH_FAIL = '@User/ORDERS_LIST_FETCH_FAIL';

export const ADD_TO_FAVORITES_REQUEST = '@User/ADD_TO_FAVORITES_REQUEST';
export const ADD_TO_FAVORITES_SUCCESS = '@User/ADD_TO_FAVORITES_SUCCESS';
export const ADD_TO_FAVORITES_FAIL = '@User/ADD_TO_FAVORITES_FAIL';

export const DELETE_FROM_FAVORITES_REQUEST = '@User/DELETE_FROM_FAVORITES_REQUEST';
export const DELETE_FROM_FAVORITES_SUCCESS = '@User/DELETE_FROM_FAVORITES_SUCCESS';
export const DELETE_FROM_FAVORITES_FAIL = '@User/DELETE_FROM_FAVORITES_FAIL';

export const FAVORITES_LIST_FETCH_REQUEST = '@User/FAVORITES_LIST_FETCH_REQUEST';
export const FAVORITES_LIST_FETCH_SUCCESS = '@User/FAVORITES_LIST_FETCH_SUCCESS';
export const FAVORITES_LIST_FETCH_FAIL = '@User/FAVORITES_LIST_FETCH_FAIL';

export const ORDER_DETAIL_FETCH_REQUEST = '@User/ORDER_DETAIL_FETCH_REQUEST';
export const ORDER_DETAIL_FETCH_SUCCESS = '@User/ORDER_DETAIL_FETCH_SUCCESS';
export const ORDER_DETAIL_FETCH_FAIL = '@User/ORDER_DETAIL_FETCH_FAIL';