export const LOGIN_USER_REQUEST = '@user/LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = '@user/LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = '@user/LOGIN_USER_FAIL';

export const REGISTER_USER_REQUEST = '@user/REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = '@user/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = '@user/REGISTER_USER_FAIL';

export const VALIDATE_NAME_REQUEST = '@user/VALIDATE_NAME_REQUEST';
export const VALIDATE_NAME_SUCCESS = '@user/VALIDATE_NAME_SUCCESS';
export const VALIDATE_NAME_FAIL = '@user/VALIDATE_NAME_FAIL';

export const VALIDATE_EMAIL_REQUEST = '@user/VALIDATE_EMAIL_REQUEST';
export const VALIDATE_EMAIL_SUCCESS = '@user/VALIDATE_EMAIL_SUCCESS';
export const VALIDATE_EMAIL_FAIL = '@user/VALIDATE_EMAIL_FAIL';

export const LOGOUT_USER = '@user/LOGOUT_USER';

export const CLEAR_ERROR_LOGIN = '@user/CLEAR_ERROR_LOGIN';

export const SAVE_ORDER_TAB_DATA = '@user/SAVE_ORDER_TAB_DATA';
export const SAVE_PAYMENT_TAB_DATA = '@user/SAVE_PAYMENT_TAB_DATA';
export const SAVE_DELIVERY_TAB_DATA = '@user/SAVE_DELIVERY_TAB_DATA';