export const PAYMENTS_DATA_FETCH_REQUEST = '@Checkout/PAYMENTS_DATA_FETCH_REQUEST';
export const PAYMENTS_DATA_FETCH_SUCCESS = '@Checkout/PAYMENTS_DATA_FETCH_SUCCESS';
export const PAYMENTS_DATA_FETCH_FAIL = '@Checkout/PAYMENTS_DATA_FETCH_FAIL';

export const FINISH_DATA_SEND_REQUEST = '@Checkout/FINISH_DATA_SEND_REQUEST';
export const FINISH_DATA_SEND_SUCCESS = '@Checkout/FINISH_DATA_SEND_SUCCESS';
export const FINISH_DATA_SEND_FAIL = '@Checkout/FINISH_DATA_SEND_FAIL';