export const PAYMENTS_DATA_FETCH_REQUEST = '@checkout/PAYMENTS_DATA_FETCH_REQUEST';
export const PAYMENTS_DATA_FETCH_SUCCESS = '@checkout/PAYMENTS_DATA_FETCH_SUCCESS';
export const PAYMENTS_DATA_FETCH_FAIL = '@checkout/PAYMENTS_DATA_FETCH_FAIL';

export const FINISH_DATA_SEND_REQUEST = '@checkout/FINISH_DATA_SEND_REQUEST';
export const FINISH_DATA_SEND_SUCCESS = '@checkout/FINISH_DATA_SEND_SUCCESS';
export const FINISH_DATA_SEND_FAIL = '@checkout/FINISH_DATA_SEND_FAIL';