export const PRODUCT_LIST_FETCH_REQUEST = '@Product/PRODUCT_LIST_FETCH_REQUEST';
export const PRODUCT_LIST_FETCH_SUCCESS = '@Product/PRODUCT_LIST_FETCH_SUCCESS';
export const PRODUCT_LIST_FETCH_FAIL = '@Product/PRODUCT_LIST_FETCH_FAIL';

export const PRODUCT_ITEM_FETCH_REQUEST = '@Product/PRODUCT_ITEM_FETCH_REQUEST';
export const PRODUCT_ITEM_FETCH_SUCCESS = '@Product/PRODUCT_ITEM_FETCH_SUCCESS';
export const PRODUCT_ITEM_FETCH_FAIL = '@Product/PRODUCT_ITEM_FETCH_FAIL';

export const CLEAR_PRODUCT_ITEM = '@Product/CLEAR_PRODUCT_ITEM';