export const PRODUCT_LIST_FETCH_REQUEST = '@product/PRODUCT_LIST_FETCH_REQUEST';
export const PRODUCT_LIST_FETCH_SUCCESS = '@product/PRODUCT_LIST_FETCH_SUCCESS';
export const PRODUCT_LIST_FETCH_FAIL = '@product/PRODUCT_LIST_FETCH_FAIL';

export const PRODUCT_ITEM_FETCH_REQUEST = '@product/PRODUCT_ITEM_FETCH_REQUEST';
export const PRODUCT_ITEM_FETCH_SUCCESS = '@product/PRODUCT_ITEM_FETCH_SUCCESS';
export const PRODUCT_ITEM_FETCH_FAIL = '@product/PRODUCT_ITEM_FETCH_FAIL';

export const CLEAR_PRODUCT_ITEM = '@product/CLEAR_PRODUCT_ITEM';