export const ORDERS_LIST_FETCH_REQUEST = '@Orders/ORDERS_LIST_FETCH_REQUEST';
export const ORDERS_LIST_FETCH_SUCCESS = '@Orders/ORDERS_LIST_FETCH_SUCCESS';
export const ORDERS_LIST_FETCH_FAIL = '@Orders/ORDERS_LIST_FETCH_FAIL';

export const ORDER_DETAIL_FETCH_REQUEST = '@Orders/ORDER_DETAIL_FETCH_REQUEST';
export const ORDER_DETAIL_FETCH_SUCCESS = '@Orders/ORDER_DETAIL_FETCH_SUCCESS';
export const ORDER_DETAIL_FETCH_FAIL = '@Orders/ORDER_DETAIL_FETCH_FAIL';

export const ACCEPT_ORDER_REQUEST = '@Orders/ACCEPT_ORDER_REQUEST';
export const ACCEPT_ORDER_SUCCESS = '@Orders/ACCEPT_ORDER_SUCCESS';
export const ACCEPT_ORDER_FAIL = '@Orders/ACCEPT_ORDER_FAIL';