export const SAVE_COMMENT_REQUEST = '@Comment/SAVE_COMMENT_REQUEST';
export const SAVE_COMMENT_SUCCESS = '@Comment/SAVE_COMMENT_SUCCESS';
export const SAVE_COMMENT_FAIL = '@Comment/SAVE_COMMENT_FAIL';

export const COMMENTS_FETCH_REQUEST = '@Comment/COMMENTS_FETCH_REQUEST';
export const COMMENTS_FETCH_SUCCESS = '@Comment/COMMENTS_FETCH_SUCCESS';
export const COMMENTS_FETCH_FAIL = '@Comment/COMMENTS_FETCH_FAIL';

export const SAVE_VOTE_REQUEST = '@Comment/SAVE_VOTE_REQUEST';
export const SAVE_VOTE_SUCCESS = '@Comment/SAVE_VOTE_SUCCESS';
export const SAVE_VOTE_FAIL = '@Comment/SAVE_VOTE_FAIL';