export const ABOUT_CONTENT_FETCH_REQUEST = '@PageContent/ABOUT_CONTENT_FETCH_REQUEST';
export const ABOUT_CONTENT_FETCH_SUCCESS = '@PageContent/ABOUT_CONTENT_FETCH_SUCCESS';
export const ABOUT_CONTENT_FETCH_FAIL = '@PageContent/ABOUT_CONTENT_FETCH_FAIL';

export const PAYMENT_CONTENT_FETCH_REQUEST = '@PageContent/PAYMENT_CONTENT_FETCH_REQUEST';
export const PAYMENT_CONTENT_FETCH_SUCCESS = '@PageContent/PAYMENT_CONTENT_FETCH_SUCCESS';
export const PAYMENT_CONTENT_FETCH_FAIL = '@PageContent/PAYMENT_CONTENT_FETCH_FAIL';

export const WARRANTY_CONTENT_FETCH_REQUEST = '@PageContent/WARRANTY_CONTENT_FETCH_REQUEST';
export const WARRANTY_CONTENT_FETCH_SUCCESS = '@PageContent/WARRANTY_CONTENT_FETCH_SUCCESS';
export const WARRANTY_CONTENT_FETCH_FAIL = '@PageContent/WARRANTY_CONTENT_FETCH_FAIL';